//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 10:50:20 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://medium.com/article", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.practice.consumesoap.stub;
